fund_id: axis-small-cap
as_of: '2026-08-24'
source: groww:axis-small-cap-fund-direct-growth
cash_pct: 14.4
holdings:
- name: Krishna Institute Of Medical Sciences Ltd
  ticker: KIMS.NS
  weight_pct: 2.808
- name: CCL Products (India) Ltd
  ticker: CCL.NS
  weight_pct: 2.704
- name: JB Chemicals & Pharmaceuticals Ltd
  ticker: BIOFILCHEM.NS
  weight_pct: 2.331
- name: City Union Bank Ltd
  ticker: CUB.NS
  weight_pct: 1.864
- name: Sai Life Sciences Ltd.
  ticker: SAILIFE.NS
  weight_pct: 1.584
- name: Cholamandalam Financial Holdings Ltd
  ticker: CHOLAHLDNG.NS
  weight_pct: 1.561
- name: HDFC Bank Ltd
  ticker: HDFCBANK.NS
  weight_pct: 1.483
- name: Craftsman Automation Ltd
  ticker: CRAFTSMAN.NS
  weight_pct: 1.443
- name: Sansera Engineering Ltd
  ticker: SANSERA.NS
  weight_pct: 1.414
- name: Brigade Enterprises Ltd
  ticker: BRIGADE.NS
  weight_pct: 1.398
- name: Kirloskar Oil Engines Ltd
  ticker: KIRLOSENG.NS
  weight_pct: 1.385
- name: Minda Corporation Ltd
  ticker: MINDACORP.NS
  weight_pct: 1.368
- name: Navin Fluorine International Ltd
  ticker: NAVINFLUOR.NS
  weight_pct: 1.367
- name: Blue Star Ltd
  ticker: BLUESTARCO.NS
  weight_pct: 1.345
- name: Multi Commodity Exchange Of India Ltd
  ticker: MCX.NS
  weight_pct: 1.331
- name: Can Fin Homes Ltd
  ticker: CANFINHOME.NS
  weight_pct: 1.258
- name: Avalon Technologies Ltd.
  ticker: AVALON.NS
  weight_pct: 1.237
- name: Karur Vysya Bank Ltd
  ticker: KARURVYSYA.NS
  weight_pct: 1.222
- name: Syrma SGS Technology Ltd
  ticker: SYRMA.NS
  weight_pct: 1.182
- name: Fine Organic Industries Ltd
  ticker: FINEORG.NS
  weight_pct: 1.141
- name: Narayana Hrudayalaya Ltd
  ticker: NH.NS
  weight_pct: 1.116
- name: Phoenix Mills Ltd
  ticker: PHOENIXLTD.NS
  weight_pct: 1.114
- name: Vesuvius India Ltd
  ticker: VESUVIUS.NS
  weight_pct: 1.075
- name: PNB Housing Finance Ltd
  ticker: PNBHOUSING.NS
  weight_pct: 1.054
- name: S.J.S Enterprises Ltd
  ticker: SJS.NS
  weight_pct: 1.039
- name: PB Fintech Ltd
  ticker: POLICYBZR.NS
  weight_pct: 0.984
- name: RBL Bank Ltd
  ticker: RBLBANK.NS
  weight_pct: 0.982
- name: Vijaya Diagnostic Centre Ltd
  ticker: VIJAYA.NS
  weight_pct: 0.949
- name: Galaxy Surfactants Ltd
  ticker: GALAXYSURF.NS
  weight_pct: 0.939
- name: Ahluwalia Contracts (India) Ltd
  ticker: AHLUCONT.NS
  weight_pct: 0.938
- name: DOMS Industries Ltd.
  ticker: DOMS.NS
  weight_pct: 0.927
- name: JK Lakshmi Cement Ltd
  ticker: JKLAKSHMI.NS
  weight_pct: 0.886
- name: Welspun Corp Ltd
  ticker: WELCORP.NS
  weight_pct: 0.884
- name: Crompton Greaves Consumer Electricals Ltd
  ticker: CROMPTON.NS
  weight_pct: 0.865
- name: Data Patterns (India) Ltd
  ticker: DATAPATTNS.NS
  weight_pct: 0.851
- name: RateGain Travel Technologies Ltd
  ticker: RATEGAIN.NS
  weight_pct: 0.845
- name: Laurus Labs Ltd
  ticker: LAURUSLABS.NS
  weight_pct: 0.835
- name: Gland Pharma Ltd
  ticker: GLAND.NS
  weight_pct: 0.808
- name: Apar Industries Ltd
  ticker: APARINDS.NS
  weight_pct: 0.79
- name: CreditAccess Grameen Ltd
  ticker: CREDITACC.NS
  weight_pct: 0.777
- name: Aditya Infotech Ltd.
  ticker: CPPLUS.NS
  weight_pct: 0.773
- name: R R Kabel Ltd.
  ticker: RRKABEL.NS
  weight_pct: 0.767
- name: Niva Bupa Health Insurance Company Ltd.
  ticker: NIVABUPA.NS
  weight_pct: 0.747
- name: Radico Khaitan Ltd
  ticker: RADICO.NS
  weight_pct: 0.744
- name: Timken India Ltd
  ticker: TIMKEN.NS
  weight_pct: 0.733
- name: Carborundum Universal Ltd
  ticker: CARBORUNIV.NS
  weight_pct: 0.725
- name: Ujjivan Small Finance Bank Ltd
  ticker: UJJIVANSFB.NS
  weight_pct: 0.723
- name: KFin Technologies Ltd
  ticker: KFINTECH.NS
  weight_pct: 0.722
- name: Union Bank of India
  ticker: UNIONBANK.NS
  weight_pct: 0.722
- name: Computer Age Management Services Ltd
  ticker: CAMS.NS
  weight_pct: 0.72
- name: Reliance Industries Ltd
  ticker: RELIANCE.NS
  weight_pct: 0.706
- name: Healthcare Global Enterprises Ltd
  ticker: HCG.NS
  weight_pct: 0.698
- name: Equitas Small Finance Bank Ltd
  ticker: EQUITASBNK.NS
  weight_pct: 0.662
- name: Grindwell Norton Ltd
  ticker: GRINDWELL.NS
  weight_pct: 0.66
- name: Kaynes Technology India Ltd
  ticker: KAYNES.NS
  weight_pct: 0.647
- name: Pine Labs Ltd.
  ticker: PINELABS.NS
  weight_pct: 0.646
- name: TBO Tek Ltd.
  ticker: TBOTEK.NS
  weight_pct: 0.632
- name: Sagility India Ltd.
  ticker: SAGILITY.NS
  weight_pct: 0.629
- name: Gujarat Fluorochemicals Ltd
  ticker: FLUOROCHEM.NS
  weight_pct: 0.626
- name: India Shelter Finance Corporation Ltd.
  ticker: INDIASHLTR.NS
  weight_pct: 0.626
- name: Mrs. Bectors Food Specialities Ltd
  ticker: BECTORFOOD.NS
  weight_pct: 0.617
- name: Gokaldas Exports Ltd
  ticker: GOKEX.NS
  weight_pct: 0.609
- name: Sudarshan Chemical Industries Ltd
  ticker: SUDARSCHEM.NS
  weight_pct: 0.584
- name: Sudeep Pharma Ltd.
  ticker: SUDEEPPHRM.NS
  weight_pct: 0.578
- name: 'Deepak Fertilisers & Petrochemicals Corporation '
  ticker: DEEPAKFERT.NS
  weight_pct: 0.572
- name: Coforge Ltd
  ticker: COFORGE.NS
  weight_pct: 0.563
- name: Neogen Chemicals Ltd
  ticker: NEOGEN.NS
  weight_pct: 0.558
- name: Balrampur Chini Mills Ltd
  ticker: BALRAMCHIN.NS
  weight_pct: 0.554
- name: Jubilant Ingrevia Ltd
  ticker: JUBLINGREA.NS
  weight_pct: 0.545
- name: RHI Magnesita India Ltd
  ticker: RHIM.NS
  weight_pct: 0.545
- name: Aditya Vision Ltd
  ticker: AVL.NS
  weight_pct: 0.54
- name: Happy Forgings Ltd.
  ticker: HAPPYFORGE.NS
  weight_pct: 0.536
- name: Aptus Value Housing Finance India Ltd
  ticker: APTUS.NS
  weight_pct: 0.532
- name: Inventurus Knowledge Solutions Ltd.
  ticker: IKS.NS
  weight_pct: 0.529
- name: Chalet Hotels Ltd
  ticker: CHALET.NS
  weight_pct: 0.518
- name: Delhivery Ltd
  ticker: DELHIVERY.NS
  weight_pct: 0.515
- name: Onesource Specialty Pharma Ltd
  ticker: ONESOURCE.NS
  weight_pct: 0.514
- name: Rainbow Childrens Medicare Ltd
  ticker: RAINBOW.NS
  weight_pct: 0.512
- name: Emcure Pharmaceuticals Ltd.
  ticker: EMCURE.NS
  weight_pct: 0.509
- name: PG Electroplast Ltd
  ticker: PGEL.NS
  weight_pct: 0.504
- name: Rolex Rings Ltd
  ticker: ROLEXRINGS.NS
  weight_pct: 0.499
- name: Coal India Ltd
  ticker: COALINDIA.NS
  weight_pct: 0.497
- name: Bharat Dynamics Ltd
  ticker: BDL.NS
  weight_pct: 0.484
- name: Tenneco Clean Air India Ltd.
  ticker: TENNIND.NS
  weight_pct: 0.484
- name: Azad Engineering Ltd.
  ticker: AZAD.NS
  weight_pct: 0.48
- name: Anant Raj Ltd
  ticker: ANANTRAJ.NS
  weight_pct: 0.469
- name: Arvind Fashions Ltd
  ticker: ARVINDFASN.NS
  weight_pct: 0.467
- name: Central Depository Services (India) Ltd
  ticker: CDSL.NS
  weight_pct: 0.465
- name: Mahanagar Gas Ltd
  ticker: MGL.NS
  weight_pct: 0.462
- name: Tech Mahindra Ltd
  ticker: TECHM.NS
  weight_pct: 0.445
- name: Amber Enterprises India Ltd
  ticker: AMBER.NS
  weight_pct: 0.443
- name: Devyani International Ltd
  ticker: DEVYANI.NS
  weight_pct: 0.429
- name: Alembic Pharmaceuticals Ltd
  ticker: APLLTD.NS
  weight_pct: 0.407
- name: Tata Consumer Products Ltd
  ticker: TATACONSUM.NS
  weight_pct: 0.404
- name: Mahindra Lifespace Developers Ltd
  ticker: MAHLIFE.NS
  weight_pct: 0.403
- name: Orient Electric Ltd
  ticker: ORIENTELEC.NS
  weight_pct: 0.402
- name: Time Technoplast Ltd
  ticker: TIMETECHNO.NS
  weight_pct: 0.393
- name: Chemplast Sanmar Ltd
  ticker: CHEMPLASTS.NS
  weight_pct: 0.391
- name: CESC Ltd
  ticker: CESC.NS
  weight_pct: 0.344
- name: Jain Resource Recycling Ltd.
  ticker: JAINREC.NS
  weight_pct: 0.338
- name: Birlasoft Ltd
  ticker: BSOFT.NS
  weight_pct: 0.327
- name: Aarti Industries Ltd
  ticker: AARTIIND.NS
  weight_pct: 0.311
- name: PNC Infratech Ltd
  ticker: PNCINFRA.NS
  weight_pct: 0.296
- name: Jyoti CNC Automation Ltd.
  ticker: JYOTICNC.NS
  weight_pct: 0.287
- name: Strides Pharma Science Ltd
  ticker: STAR.NS
  weight_pct: 0.273
- name: Havells India Ltd
  ticker: HAVELLS.NS
  weight_pct: 0.251
- name: Heidelberg Cement India Ltd
  ticker: HEIDELBERG.NS
  weight_pct: 0.25
- name: Midwest Ltd.
  ticker: MIDWESTLTD.NS
  weight_pct: 0.241
- name: Alicon Castalloy Ltd
  ticker: ALICON.NS
  weight_pct: 0.228
- name: Suprajit Engineering Ltd
  ticker: SUPRAJIT.NS
  weight_pct: 0.217
- name: Ellenbarrie Industrial Gases Ltd
  ticker: ELLEN.NS
  weight_pct: 0.211
- name: Travel Food Services Ltd.
  ticker: TRAVELFOOD.NS
  weight_pct: 0.202
- name: SBFC Finance Ltd
  ticker: SBFC.NS
  weight_pct: 0.197
- name: Whirlpool Of India Ltd
  ticker: WHIRLPOOL.NS
  weight_pct: 0.192
- name: Power Grid Corporation of India Ltd
  ticker: POWERGRID.NS
  weight_pct: 0.182
- name: PDS Ltd
  ticker: PDSL.NS
  weight_pct: 0.174
- name: Firstsource Solutions Ltd
  ticker: FSL.NS
  weight_pct: 0.171
- name: Engineers India Ltd
  ticker: ENGINERSIN.NS
  weight_pct: 0.167
- name: TeamLease Services Ltd
  ticker: TEAMLEASE.NS
  weight_pct: 0.09
- name: Ather Energy Ltd.
  ticker: ATHERENERG.NS
  weight_pct: 0.067
- name: Tata Consultancy Services Ltd
  ticker: TCS.NS
  weight_pct: 0.042
- name: Jyothy Labs Ltd
  ticker: JYOTHYLAB.NS
  weight_pct: 0.033
