fund_id: jioblackrock-flexicap
as_of: '2026-09-12'
source: groww:jioblackrock-flexi-cap-fund-direct-growth
cash_pct: 8.27
holdings:
- name: HDFC Bank Ltd
  ticker: HDFCBANK.NS
  weight_pct: 6.39
- name: ICICI Bank Ltd
  ticker: ICICIBANK.NS
  weight_pct: 6.0
- name: Bharti Airtel Ltd
  ticker: BHARTIARTL.NS
  weight_pct: 4.495
- name: Reliance Industries Ltd
  ticker: RELIANCE.NS
  weight_pct: 3.558
- name: Mahindra & Mahindra Ltd
  ticker: M&M.NS
  weight_pct: 3.063
- name: Tata Steel Ltd
  ticker: TATASTEEL.NS
  weight_pct: 2.284
- name: Larsen & Toubro Ltd
  ticker: LT.NS
  weight_pct: 2.266
- name: Infosys Ltd
  ticker: INFY.NS
  weight_pct: 2.231
- name: State Bank of India
  ticker: SBIN.NS
  weight_pct: 1.916
- name: Nestle India Ltd
  ticker: NESTLEIND.NS
  weight_pct: 1.847
- name: Oil & Natural Gas Corporation Ltd
  ticker: ONGC.NS
  weight_pct: 1.729
- name: Bajaj Finserv Ltd
  ticker: BAJAJFINSV.NS
  weight_pct: 1.709
- name: Steel Authority Of India Ltd
  ticker: SAIL.NS
  weight_pct: 1.632
- name: Polycab India Ltd
  ticker: POLYCAB.NS
  weight_pct: 1.583
- name: Navin Fluorine International Ltd
  ticker: NAVINFLUOR.NS
  weight_pct: 1.578
- name: Indian Oil Corporation Ltd
  ticker: IOC.NS
  weight_pct: 1.57
- name: Apollo Tyres Ltd
  ticker: APOLLOTYRE.NS
  weight_pct: 1.508
- name: Asian Paints Ltd
  ticker: ASIANPAINT.NS
  weight_pct: 1.447
- name: Ultratech Cement Ltd
  ticker: ULTRACEMCO.NS
  weight_pct: 1.401
- name: ITC Ltd
  ticker: ITC.NS
  weight_pct: 1.284
- name: Nippon Life India Asset Management Ltd
  ticker: NAM-INDIA.NS
  weight_pct: 1.283
- name: Tata Consultancy Services Ltd
  ticker: TCS.NS
  weight_pct: 1.26
- name: Life Insurance Corporation of India
  ticker: LICI.NS
  weight_pct: 1.222
- name: NTPC Ltd
  ticker: NTPC.NS
  weight_pct: 1.219
- name: Lupin Ltd
  ticker: LUPIN.NS
  weight_pct: 1.204
- name: Hero Motocorp Ltd
  ticker: HEROMOTOCO.NS
  weight_pct: 1.179
- name: Multi Commodity Exchange Of India Ltd
  ticker: MCX.NS
  weight_pct: 1.127
- name: Titan Company Ltd
  ticker: TITAN.NS
  weight_pct: 1.095
- name: JSW Steel Ltd
  ticker: JSWSTEEL.NS
  weight_pct: 1.066
- name: Lenskart Solutions Ltd.
  ticker: LENSKART.NS
  weight_pct: 1.061
- name: HCL Technologies Ltd
  ticker: HCLTECH.NS
  weight_pct: 0.993
- name: Coal India Ltd
  ticker: COALINDIA.NS
  weight_pct: 0.993
- name: Yes Bank Ltd
  ticker: YESBANK.NS
  weight_pct: 0.991
- name: Bharat Heavy Electricals Ltd
  ticker: BHEL.NS
  weight_pct: 0.981
- name: Punjab National Bank
  ticker: PNB.NS
  weight_pct: 0.944
- name: BSE Ltd
  ticker: BSE.NS
  weight_pct: 0.928
- name: Elgi Equipments Ltd
  ticker: ELGIEQUIP.NS
  weight_pct: 0.927
- name: Laurus Labs Ltd
  ticker: LAURUSLABS.NS
  weight_pct: 0.837
- name: Radico Khaitan Ltd
  ticker: RADICO.NS
  weight_pct: 0.832
- name: Tata Motors Ltd
  ticker: TMCV.NS
  weight_pct: 0.81
- name: Dr. Lal Pathlabs Ltd
  ticker: LALPATHLAB.NS
  weight_pct: 0.801
- name: Indraprastha Gas Ltd
  ticker: IGL.NS
  weight_pct: 0.68
- name: Jamna Auto Industries Ltd
  ticker: JAMNAAUTO.NS
  weight_pct: 0.649
- name: ICICI Prudential Asset Management Company Ltd.
  ticker: ICICIAMC.NS
  weight_pct: 0.645
- name: Max Financial Services Ltd
  ticker: MFSL.NS
  weight_pct: 0.617
- name: CESC Ltd
  ticker: CESC.NS
  weight_pct: 0.601
- name: The Great Eastern Shipping Company Ltd
  ticker: GESHIP.NS
  weight_pct: 0.601
- name: Hindalco Industries Ltd
  ticker: HINDALCO.NS
  weight_pct: 0.554
- name: Billionbrains Garage Ventures Ltd.
  ticker: GROWW.NS
  weight_pct: 0.553
- name: Karur Vysya Bank Ltd
  ticker: KARURVYSYA.NS
  weight_pct: 0.533
- name: Bandhan Bank Ltd
  ticker: BANDHANBNK.NS
  weight_pct: 0.512
- name: Axis Bank Ltd
  ticker: AXISBANK.NS
  weight_pct: 0.506
- name: Ashok Leyland Ltd
  ticker: ASHOKLEY.NS
  weight_pct: 0.503
- name: Sun Pharmaceutical Industries Ltd
  ticker: SUNPHARMA.NS
  weight_pct: 0.502
- name: Thermax Ltd
  ticker: THERMAX.NS
  weight_pct: 0.499
- name: R R Kabel Ltd.
  ticker: RRKABEL.NS
  weight_pct: 0.497
- name: Honasa Consumer Ltd.
  ticker: HONASA.NS
  weight_pct: 0.433
- name: Samvardhana Motherson International Ltd
  ticker: MOTHERSON.NS
  weight_pct: 0.409
- name: PTC India Ltd
  ticker: PTC.NS
  weight_pct: 0.395
- name: Power Finance Corporation Ltd
  ticker: PFC.NS
  weight_pct: 0.378
- name: The Jammu & Kashmir Bank Ltd
  ticker: J&KBANK.NS
  weight_pct: 0.376
- name: Bajaj Finance Ltd
  ticker: BAJFINANCE.NS
  weight_pct: 0.365
- name: Minda Corporation Ltd
  ticker: MINDACORP.NS
  weight_pct: 0.364
- name: Ujjivan Small Finance Bank Ltd
  ticker: UJJIVANSFB.NS
  weight_pct: 0.352
- name: Aditya Infotech Ltd.
  ticker: CPPLUS.NS
  weight_pct: 0.323
- name: AIA Engineering Ltd
  ticker: AIAENG.NS
  weight_pct: 0.316
- name: Akums Drugs And Pharmaceuticals Ltd.
  ticker: AKUMS.NS
  weight_pct: 0.315
- name: Bajaj Holdings & Investment Ltd
  ticker: BAJAJHLDNG.NS
  weight_pct: 0.312
- name: Berger Paints India Ltd
  ticker: BERGEPAINT.NS
  weight_pct: 0.307
- name: Bharat Petroleum Corporation Ltd
  ticker: BPCL.NS
  weight_pct: 0.295
- name: Siemens Energy India Ltd
  ticker: ENRIN.NS
  weight_pct: 0.29
- name: Kirloskar Oil Engines Ltd
  ticker: KIRLOSENG.NS
  weight_pct: 0.288
- name: Arvind Ltd
  ticker: ARVIND.NS
  weight_pct: 0.288
- name: Sterlite Technologies Ltd
  ticker: STLTECH.NS
  weight_pct: 0.283
- name: Syrma SGS Technology Ltd
  ticker: SYRMA.NS
  weight_pct: 0.273
- name: Kansai Nerolac Paints Ltd
  ticker: KANSAINER.NS
  weight_pct: 0.266
- name: Apar Industries Ltd
  ticker: APARINDS.NS
  weight_pct: 0.261
- name: Shipping Corporation Of India Ltd
  ticker: SCI.NS
  weight_pct: 0.254
- name: Marico Ltd
  ticker: MARICO.NS
  weight_pct: 0.232
- name: JM Financial Ltd
  ticker: JMFINANCIL.NS
  weight_pct: 0.228
- name: DLF Ltd
  ticker: DLF.NS
  weight_pct: 0.223
- name: Bombay Burmah Trading Corporation Ltd
  ticker: BBTC.NS
  weight_pct: 0.206
- name: Hindustan Zinc Ltd
  ticker: HINDZINC.NS
  weight_pct: 0.204
- name: Mahindra & Mahindra Financial Services Ltd
  ticker: M&MFIN.NS
  weight_pct: 0.197
- name: Ceat Ltd
  ticker: CEATLTD.NS
  weight_pct: 0.197
- name: The Federal Bank Ltd
  ticker: FEDERALBNK.NS
  weight_pct: 0.191
- name: Hitachi Energy India Ltd
  ticker: POWERINDIA.NS
  weight_pct: 0.186
- name: Ather Energy Ltd.
  ticker: ATHERENERG.NS
  weight_pct: 0.185
- name: Rubicon Research Ltd.
  ticker: RUBICON.NS
  weight_pct: 0.176
- name: Edelweiss Financial Services Ltd
  ticker: EDELWEISS.NS
  weight_pct: 0.176
- name: Glenmark Pharmaceuticals Ltd
  ticker: GLENMARK.NS
  weight_pct: 0.162
- name: Hindustan Petroleum Corporation Ltd
  ticker: HINDPETRO.NS
  weight_pct: 0.159
- name: WeWork India Management Ltd.
  ticker: WEWORK.NS
  weight_pct: 0.149
- name: MTAR Technologies Ltd
  ticker: MTARTECH.NS
  weight_pct: 0.147
- name: National Aluminium Company Ltd
  ticker: NATIONALUM.NS
  weight_pct: 0.141
- name: Avalon Technologies Ltd.
  ticker: AVALON.NS
  weight_pct: 0.14
- name: Granules India Ltd
  ticker: GRANULES.NS
  weight_pct: 0.129
- name: CCL Products (India) Ltd
  ticker: CCL.NS
  weight_pct: 0.126
- name: Natco Pharma Ltd
  ticker: NATCOPHARM.NS
  weight_pct: 0.12
- name: Atul Ltd
  ticker: ATUL.NS
  weight_pct: 0.099
- name: FSN E-Commerce Ventures Ltd
  ticker: NYKAA.NS
  weight_pct: 0.097
- name: Escorts Kubota Ltd
  ticker: ESCORTS.NS
  weight_pct: 0.094
- name: Power Grid Corporation of India Ltd
  ticker: POWERGRID.NS
  weight_pct: 0.088
- name: Strides Pharma Science Ltd
  ticker: STAR.NS
  weight_pct: 0.088
- name: Kajaria Ceramics Ltd
  ticker: KAJARIACER.NS
  weight_pct: 0.088
- name: VA Tech Wabag Ltd
  ticker: WABAG.NS
  weight_pct: 0.086
- name: Delhivery Ltd
  ticker: DELHIVERY.NS
  weight_pct: 0.085
- name: General Insurance Corporation of India Ltd
  ticker: GICRE.NS
  weight_pct: 0.082
- name: Kalyan Jewellers India Ltd
  ticker: KALYANKJIL.NS
  weight_pct: 0.076
- name: Aurobindo Pharma Ltd
  ticker: AUROPHARMA.NS
  weight_pct: 0.07
- name: Marksans Pharma Ltd
  ticker: MARKSANS.NS
  weight_pct: 0.068
- name: Advanced Enzyme Technologies Ltd
  ticker: ADVENZYMES.NS
  weight_pct: 0.065
- name: TVS Supply Chain Solutions Ltd.
  ticker: TVSSCS.NS
  weight_pct: 0.056
- name: Fiem Industries Ltd
  ticker: FIEMIND.NS
  weight_pct: 0.053
- name: LIC Housing Finance Ltd
  ticker: LICHSGFIN.NS
  weight_pct: 0.052
- name: GMM Pfaudler Ltd
  ticker: GMMPFAUDLR.NS
  weight_pct: 0.05
- name: Ahluwalia Contracts (India) Ltd
  ticker: AHLUCONT.NS
  weight_pct: 0.047
- name: Godrej Agrovet Ltd
  ticker: GODREJAGRO.NS
  weight_pct: 0.044
- name: ICICI Prudential Life Insurance Company Ltd
  ticker: ICICIPRULI.NS
  weight_pct: 0.039
- name: Nava Ltd
  ticker: NAVA.NS
  weight_pct: 0.035
- name: Birla Corporation Ltd
  ticker: BIRLACORPN.NS
  weight_pct: 0.034
