fund_id: mirae-large-midcap
as_of: '2026-08-24'
source: groww:mirae-asset-large-midcap-fund-direct-growth
cash_pct: 3.77
holdings:
- name: HDFC Bank Ltd
  ticker: HDFCBANK.NS
  weight_pct: 6.69
- name: ICICI Bank Ltd
  ticker: ICICIBANK.NS
  weight_pct: 3.835
- name: Reliance Industries Ltd
  ticker: RELIANCE.NS
  weight_pct: 3.239
- name: Laurus Labs Ltd
  ticker: LAURUSLABS.NS
  weight_pct: 3.195
- name: State Bank of India
  ticker: SBIN.NS
  weight_pct: 3.098
- name: Axis Bank Ltd
  ticker: AXISBANK.NS
  weight_pct: 2.885
- name: Tata Communications Ltd
  ticker: TATACOMM.NS
  weight_pct: 2.294
- name: PB Fintech Ltd
  ticker: POLICYBZR.NS
  weight_pct: 2.178
- name: Delhivery Ltd
  ticker: DELHIVERY.NS
  weight_pct: 2.117
- name: Lupin Ltd
  ticker: LUPIN.NS
  weight_pct: 2.026
- name: SBI Life Insurance Company Ltd
  ticker: SBILIFE.NS
  weight_pct: 1.974
- name: Indusind Bank Ltd
  ticker: INDUSINDBK.NS
  weight_pct: 1.973
- name: Hero Motocorp Ltd
  ticker: HEROMOTOCO.NS
  weight_pct: 1.964
- name: HDB FINANCIAL SERVICES LIMITED EQ
  ticker: HDBFS.NS
  weight_pct: 1.852
- name: Bharti Airtel Ltd
  ticker: BHARTIARTL.NS
  weight_pct: 1.836
- name: Bharat Forge Ltd
  ticker: BHARATFORG.NS
  weight_pct: 1.756
- name: FSN E-Commerce Ventures Ltd
  ticker: NYKAA.NS
  weight_pct: 1.741
- name: Prestige Estates Projects Ltd
  ticker: PRESTIGE.NS
  weight_pct: 1.733
- name: Narayana Hrudayalaya Ltd
  ticker: NH.NS
  weight_pct: 1.721
- name: Vedanta Aluminium Metal Ltd
  ticker: VAML.NS
  weight_pct: 1.691
- name: Tata Consultancy Services Ltd
  ticker: TCS.NS
  weight_pct: 1.664
- name: Dalmia Bharat Ltd
  ticker: DALBHARAT.NS
  weight_pct: 1.646
- name: Gland Pharma Ltd
  ticker: GLAND.NS
  weight_pct: 1.614
- name: Steel Authority Of India Ltd
  ticker: SAIL.NS
  weight_pct: 1.588
- name: Sun Pharmaceutical Industries Ltd
  ticker: SUNPHARMA.NS
  weight_pct: 1.478
- name: Swiggy Ltd.
  ticker: SWIGGY.NS
  weight_pct: 1.362
- name: Larsen & Toubro Ltd
  ticker: LT.NS
  weight_pct: 1.315
- name: Container Corporation Of India Ltd
  ticker: CONCOR.NS
  weight_pct: 1.243
- name: Infosys Ltd
  ticker: INFY.NS
  weight_pct: 1.228
- name: Lenskart Solutions Ltd.
  ticker: LENSKART.NS
  weight_pct: 1.22
- name: Ceat Ltd
  ticker: CEATLTD.NS
  weight_pct: 1.203
- name: Go Digit General Insurance Ltd.
  ticker: GODIGIT.NS
  weight_pct: 1.201
- name: Crompton Greaves Consumer Electricals Ltd
  ticker: CROMPTON.NS
  weight_pct: 1.2
- name: ITC Ltd
  ticker: ITC.NS
  weight_pct: 1.2
- name: Multi Commodity Exchange Of India Ltd
  ticker: MCX.NS
  weight_pct: 1.143
- name: Interglobe Aviation Ltd
  ticker: INDIGO.NS
  weight_pct: 1.137
- name: Tata Motors Ltd
  ticker: TMCV.NS
  weight_pct: 1.117
- name: Kotak Mahindra Bank Ltd
  ticker: KOTAKBANK.NS
  weight_pct: 1.009
- name: Gujarat Fluorochemicals Ltd
  ticker: FLUOROCHEM.NS
  weight_pct: 1.009
- name: SRF Ltd
  ticker: SRF.NS
  weight_pct: 1.006
- name: NTPC Ltd
  ticker: NTPC.NS
  weight_pct: 0.948
- name: Tata Power Company Ltd
  ticker: TATAPOWER.NS
  weight_pct: 0.943
- name: SKF India (Industrial) Ltd
  ticker: SKFINDUS.NS
  weight_pct: 0.926
- name: PI Industries Ltd
  ticker: PIIND.NS
  weight_pct: 0.924
- name: Aditya Birla Capital Ltd
  ticker: ABCAPITAL.NS
  weight_pct: 0.916
- name: Dixon Technologies (India) Ltd
  ticker: DIXON.NS
  weight_pct: 0.91
- name: Apollo Hospitals Enterprise Ltd
  ticker: APOLLOHOSP.NS
  weight_pct: 0.864
- name: One 97 Communications Ltd
  ticker: PAYTM.NS
  weight_pct: 0.86
- name: Billionbrains Garage Ventures Ltd.
  ticker: GROWW.NS
  weight_pct: 0.853
- name: United Spirits Ltd
  ticker: UNITDSPR.NS
  weight_pct: 0.833
- name: Mahindra & Mahindra Ltd
  ticker: M&M.NS
  weight_pct: 0.798
- name: Bharat Electronics Ltd
  ticker: BEL.NS
  weight_pct: 0.778
- name: Bharat Heavy Electricals Ltd
  ticker: BHEL.NS
  weight_pct: 0.774
- name: SKF India Ltd
  ticker: SKFINDIA.NS
  weight_pct: 0.768
- name: Bata India Ltd
  ticker: BATAINDIA.NS
  weight_pct: 0.76
- name: Century Plyboards (India) Ltd
  ticker: CENTURYPLY.NS
  weight_pct: 0.736
- name: Oil & Natural Gas Corporation Ltd
  ticker: ONGC.NS
  weight_pct: 0.734
- name: Hindustan Petroleum Corporation Ltd
  ticker: HINDPETRO.NS
  weight_pct: 0.672
- name: Hindustan Aeronautics Ltd
  ticker: HAL.NS
  weight_pct: 0.613
- name: Persistent Systems Ltd
  ticker: PERSISTENT.NS
  weight_pct: 0.594
- name: Titan Company Ltd
  ticker: TITAN.NS
  weight_pct: 0.536
- name: HDFC Asset Management Company Ltd
  ticker: HDFCAMC.NS
  weight_pct: 0.528
- name: Maruti Suzuki India Ltd
  ticker: MARUTI.NS
  weight_pct: 0.498
- name: Power Finance Corporation Ltd
  ticker: PFC.NS
  weight_pct: 0.454
- name: DLF Ltd
  ticker: DLF.NS
  weight_pct: 0.447
- name: Syngene International Ltd
  ticker: SYNGENE.NS
  weight_pct: 0.4
- name: JSW Energy Ltd
  ticker: JSWENERGY.NS
  weight_pct: 0.394
- name: Ola Electric Mobility Ltd.
  ticker: OLAELEC.NS
  weight_pct: 0.292
- name: Prince Pipes & Fittings Ltd
  ticker: PRINCEPIPE.NS
  weight_pct: 0.292
- name: Divi's Laboratories Ltd
  ticker: DIVISLAB.NS
  weight_pct: 0.278
- name: Cummins India Ltd
  ticker: CUMMINSIND.NS
  weight_pct: 0.255
- name: Gateway Distriparks Ltd
  ticker: GATEWAY.NS
  weight_pct: 0.169
- name: Tata Steel Ltd
  ticker: TATASTEEL.NS
  weight_pct: 0.129
- name: Vedanta Oil and Gas Ltd
  ticker: VOGL.NS
  weight_pct: 0.102
- name: Vedanta Power Ltd
  ticker: VEDPOWER.NS
  weight_pct: 0.082
- name: The Federal Bank Ltd
  ticker: FEDERALBNK.NS
  weight_pct: 0.082
- name: Grasim Industries Ltd
  ticker: GRASIM.NS
  weight_pct: 0.003
- name: Tata Motors Ltd
  ticker: TMCV.NS
  weight_pct: 0.003
- name: Hindalco Industries Ltd
  ticker: HINDALCO.NS
  weight_pct: 0.002
