fund_id: mirae-large-midcap
as_of: '2026-09-12'
source: groww:mirae-asset-large-midcap-fund-direct-growth
cash_pct: 3.49
holdings:
- name: HDFC Bank Ltd
  ticker: HDFCBANK.NS
  weight_pct: 6.229
- name: ICICI Bank Ltd
  ticker: ICICIBANK.NS
  weight_pct: 3.894
- name: Laurus Labs Ltd
  ticker: LAURUSLABS.NS
  weight_pct: 3.72
- name: Axis Bank Ltd
  ticker: AXISBANK.NS
  weight_pct: 3.246
- name: Reliance Industries Ltd
  ticker: RELIANCE.NS
  weight_pct: 3.186
- name: State Bank of India
  ticker: SBIN.NS
  weight_pct: 3.016
- name: PB Fintech Ltd
  ticker: POLICYBZR.NS
  weight_pct: 2.309
- name: Delhivery Ltd
  ticker: DELHIVERY.NS
  weight_pct: 2.102
- name: SBI Life Insurance Company Ltd
  ticker: SBILIFE.NS
  weight_pct: 2.047
- name: Hero Motocorp Ltd
  ticker: HEROMOTOCO.NS
  weight_pct: 1.998
- name: Steel Authority Of India Ltd
  ticker: SAIL.NS
  weight_pct: 1.986
- name: Indusind Bank Ltd
  ticker: INDUSINDBK.NS
  weight_pct: 1.972
- name: Lupin Ltd
  ticker: LUPIN.NS
  weight_pct: 1.968
- name: Bharti Airtel Ltd
  ticker: BHARTIARTL.NS
  weight_pct: 1.902
- name: Tata Communications Ltd
  ticker: TATACOMM.NS
  weight_pct: 1.868
- name: Dalmia Bharat Ltd
  ticker: DALBHARAT.NS
  weight_pct: 1.834
- name: Tata Consultancy Services Ltd
  ticker: TCS.NS
  weight_pct: 1.781
- name: Bharat Forge Ltd
  ticker: BHARATFORG.NS
  weight_pct: 1.752
- name: Narayana Hrudayalaya Ltd
  ticker: NH.NS
  weight_pct: 1.723
- name: Vedanta Aluminium Metal Ltd
  ticker: VAML.NS
  weight_pct: 1.666
- name: HDB FINANCIAL SERVICES LIMITED EQ
  ticker: HDBFS.NS
  weight_pct: 1.647
- name: Persistent Systems Ltd
  ticker: PERSISTENT.NS
  weight_pct: 1.587
- name: Swiggy Ltd.
  ticker: SWIGGY.NS
  weight_pct: 1.577
- name: Prestige Estates Projects Ltd
  ticker: PRESTIGE.NS
  weight_pct: 1.525
- name: Larsen & Toubro Ltd
  ticker: LT.NS
  weight_pct: 1.491
- name: FSN E-Commerce Ventures Ltd
  ticker: NYKAA.NS
  weight_pct: 1.473
- name: Sun Pharmaceutical Industries Ltd
  ticker: SUNPHARMA.NS
  weight_pct: 1.459
- name: Maruti Suzuki India Ltd
  ticker: MARUTI.NS
  weight_pct: 1.439
- name: Gland Pharma Ltd
  ticker: GLAND.NS
  weight_pct: 1.357
- name: Infosys Ltd
  ticker: INFY.NS
  weight_pct: 1.349
- name: Hindalco Industries Ltd
  ticker: HINDALCO.NS
  weight_pct: 1.348
- name: Container Corporation Of India Ltd
  ticker: CONCOR.NS
  weight_pct: 1.337
- name: Interglobe Aviation Ltd
  ticker: INDIGO.NS
  weight_pct: 1.186
- name: Ceat Ltd
  ticker: CEATLTD.NS
  weight_pct: 1.153
- name: Dixon Technologies (India) Ltd
  ticker: DIXON.NS
  weight_pct: 1.137
- name: One 97 Communications Ltd
  ticker: PAYTM.NS
  weight_pct: 1.133
- name: Tata Power Company Ltd
  ticker: TATAPOWER.NS
  weight_pct: 1.121
- name: Crompton Greaves Consumer Electricals Ltd
  ticker: CROMPTON.NS
  weight_pct: 1.106
- name: ITC Ltd
  ticker: ITC.NS
  weight_pct: 1.102
- name: Kotak Mahindra Bank Ltd
  ticker: KOTAKBANK.NS
  weight_pct: 0.977
- name: Lenskart Solutions Ltd.
  ticker: LENSKART.NS
  weight_pct: 0.974
- name: PI Industries Ltd
  ticker: PIIND.NS
  weight_pct: 0.968
- name: Multi Commodity Exchange Of India Ltd
  ticker: MCX.NS
  weight_pct: 0.936
- name: Go Digit General Insurance Ltd.
  ticker: GODIGIT.NS
  weight_pct: 0.921
- name: Billionbrains Garage Ventures Ltd.
  ticker: GROWW.NS
  weight_pct: 0.905
- name: NTPC Ltd
  ticker: NTPC.NS
  weight_pct: 0.898
- name: SRF Ltd
  ticker: SRF.NS
  weight_pct: 0.893
- name: Aditya Birla Capital Ltd
  ticker: ABCAPITAL.NS
  weight_pct: 0.893
- name: Gujarat Fluorochemicals Ltd
  ticker: FLUOROCHEM.NS
  weight_pct: 0.882
- name: Mahindra & Mahindra Ltd
  ticker: M&M.NS
  weight_pct: 0.859
- name: Tata Motors Ltd
  ticker: TMCV.NS
  weight_pct: 0.844
- name: SKF India (Industrial) Ltd
  ticker: SKFINDUS.NS
  weight_pct: 0.832
- name: United Spirits Ltd
  ticker: UNITDSPR.NS
  weight_pct: 0.806
- name: Divi's Laboratories Ltd
  ticker: DIVISLAB.NS
  weight_pct: 0.803
- name: Bharat Electronics Ltd
  ticker: BEL.NS
  weight_pct: 0.798
- name: Century Plyboards (India) Ltd
  ticker: CENTURYPLY.NS
  weight_pct: 0.764
- name: Bata India Ltd
  ticker: BATAINDIA.NS
  weight_pct: 0.753
- name: Oil & Natural Gas Corporation Ltd
  ticker: ONGC.NS
  weight_pct: 0.67
- name: Hindustan Petroleum Corporation Ltd
  ticker: HINDPETRO.NS
  weight_pct: 0.662
- name: SKF India Ltd
  ticker: SKFINDIA.NS
  weight_pct: 0.659
- name: Hindustan Aeronautics Ltd
  ticker: HAL.NS
  weight_pct: 0.632
- name: Apollo Hospitals Enterprise Ltd
  ticker: APOLLOHOSP.NS
  weight_pct: 0.345
- name: KFin Technologies Ltd
  ticker: KFINTECH.NS
  weight_pct: 0.339
- name: Prince Pipes & Fittings Ltd
  ticker: PRINCEPIPE.NS
  weight_pct: 0.261
- name: Ola Electric Mobility Ltd.
  ticker: OLAELEC.NS
  weight_pct: 0.251
- name: Cummins India Ltd
  ticker: CUMMINSIND.NS
  weight_pct: 0.242
- name: HDFC Asset Management Company Ltd
  ticker: HDFCAMC.NS
  weight_pct: 0.226
- name: Tata Steel Ltd
  ticker: TATASTEEL.NS
  weight_pct: 0.219
- name: Manipal Health Enterprises Ltd
  ticker: MANIPALHOS.NS
  weight_pct: 0.183
- name: Gateway Distriparks Ltd
  ticker: GATEWAY.NS
  weight_pct: 0.165
- name: Syngene International Ltd
  ticker: SYNGENE.NS
  weight_pct: 0.051
- name: Bharat Heavy Electricals Ltd
  ticker: BHEL.NS
  weight_pct: 0.047
- name: The Federal Bank Ltd
  ticker: FEDERALBNK.NS
  weight_pct: 0.037
- name: JSW Energy Ltd
  ticker: JSWENERGY.NS
  weight_pct: 0.028
- name: Titan Company Ltd
  ticker: TITAN.NS
  weight_pct: 0.02
- name: Power Finance Corporation Ltd
  ticker: PFC.NS
  weight_pct: 0.019
- name: DLF Ltd
  ticker: DLF.NS
  weight_pct: 0.019
- name: Grasim Industries Ltd
  ticker: GRASIM.NS
  weight_pct: 0.003
- name: Tata Motors Ltd
  ticker: TMCV.NS
  weight_pct: 0.003
